\input texinfo @c -*-texinfo-*-
@c %**start of header
@setfilename PictureDocument.info
@settitle Picture Document
@set Manual PictureDocument

@c Define a new index for options.
@defcodeindex op
@c Combine everything into one index (arbitrarily chosen to be the
@c concept index).
@syncodeindex op cp
@c %**end of header
@image{images/IMG_1276,,80pt,Picture of Anthony Bradford,jpg}

@copying
Copyright @copyright{} 2012 Anthony G. Bradford.

@quotation
All right reserved.
@end quotation
@end copying

@dircategory Picture Document
@direntry
* Picture Document Template.               Template
@end direntry

@titlepage
@title Picture Document
@subtitle for version @today{}
@sp 10
@author Anthony G. Bradford (@email{anthony_bradford@@yahoo.com})
@page
@vskip 0pt plus 1filll
@insertcopying
@end titlepage

@ifnothtml
@contents
@end ifnothtml

@ifnottex
@node Top
@top Picture Document Version @today{}

Copyright @copyright{} 2012 Anthony G. Bradford.
@end ifnottex

@html
@ifset PDF
<a href="@value{Manual}.pdf">PDF content of this website</a>
<br>
@end ifset
@ifset DJVU
<a href="@value{Manual}.djvu">DjVu content of this website</a>
<br>
@end ifset
@ifset SPLIT
<a href="index.html">Split HTML content of this website</a>
<br>
@end ifset
@ifset NOSPLIT
<a href="indexNoSplit.html">Non-Split HTML content of this website</a>
<br>
@end ifset
@ifset TEXT
@cindex Text
@cindex Plain Text
<a href="@value{Manual}.txt">Text content of this website</a> 
<br>
@end ifset
@ifset EPUB
@cindex EPUB
<a href="@value{Manual}.epub">EPUB content of this website</a> 
<br>
@end ifset
@ifset POSTSCRIPT
@cindex PostScript
<a href="@value{Manual}.ps">PostScript content of this website</a> 
<br>
@end ifset
@ifset DVI
@cindex @TeX{} DVI
@cindex DVI
<a href="@value{Manual}.dvi">@TeX{} DVI content of this website</a> 
<br>
@end ifset
@ifset ZIP
@cindex Zip
<a href="@value{Manual}.zip">HTML zip package of this website</a>
<br>
@end ifset
<a href="@value{Manual}.tar.gz">Gzipped tar source of this website</a> 
<br>
<br>
@end html

@ifnottex
@menu
* Pictures::
* Concept index::	Index of concepts.
@end menu
@end ifnottex

@html
@c @contents
@end html

@node Pictures
@unnumbered Pictures
@cindex Anthony Bradford Pictures
Just some pictures
@*
@image{images/IMG_1276,,280pt,Anthony Bradford,jpg}
@*
@*
@image{images/IMG_7620,,280pt,Anthony Bradford,jpg}
@*
@*
@image{images/IMG_7702,,280pt,Anthony Bradford,jpg}
@*
@*
@image{images/IMG_7701,,280pt,Anthony Bradford,jpg}
@*
@*
@image{images/IMG_7975,,280pt,Anthony Bradford,jpg}
@*
@*
@image{images/IMG_8654,,280pt,Anthony Bradford,jpg}
@*
@*

@node Concept index
@unnumbered Concept index
@printindex cp

@bye
