\input texinfo @c -*-texinfo-*-
@c %**start of header
@set Manual GenericUnnumbered
@setfilename @value{Manual}.info
@settitle Texinfo Templates

@c Define a new index for options.
@defcodeindex op
@c Combine everything into one index (arbitrarily chosen to be the
@c concept index).
@syncodeindex op cp
@c %**end of header
@image{images/open_book_blue,,80pt,Picture of a open book,png}

@copying
This is a template for a website. Copyright @copyright{} 2012.

@quotation
All right reserved.
@end quotation
@end copying

@dircategory Template
@direntry
* The Texinfo Website Template.               Test
@end direntry

@titlepage
@title Texinfo Website Template
@subtitle for version @today{}
@sp 10
@author @email{anthony_bradford@@yahoo.com,Anthony Bradford}
@page
@vskip 0pt plus 1filll
@insertcopying
@end titlepage

@ifnothtml
@contents
@end ifnothtml

@ifnottex
@node Top
@top Texinfo Website Template Version @today{}
 
This is a Texinfo Template Website. Copyright @copyright{} 2012.
@end ifnottex

@html
@ifset PDF
<a href="@value{Manual}.pdf">PDF content of this website</a>
<br>
@end ifset
@ifset DJVU
<a href="@value{Manual}.djvu">DjVu content of this website</a>
<br>
@end ifset
@ifset SPLIT
<a href="index.html">Split HTML content of this website</a>
<br>
@end ifset
@ifset NOSPLIT
<a href="indexNoSplit.html">Non-Split HTML content of this website</a>
<br>
@end ifset
@ifset ZIP
@cindex Zip
<a href="@value{Manual}.zip">HTML zip package of this website</a>
<br>
@end ifset
@ifset TEXT
@cindex Text
@cindex Plain Text
<a href="@value{Manual}.txt">Text content of this website</a> 
<br>
@end ifset
@ifset EPUB
@cindex EPUB
<a href="@value{Manual}.epub">EPUB content of this website</a> 
<br>
@end ifset
@ifset POSTSCRIPT
@cindex PostScript
<a href="@value{Manual}.ps">PostScript content of this website</a> 
<br>
@end ifset
@ifset DVI
@cindex @TeX{} DVI
@cindex DVI
<a href="@value{Manual}.dvi">@TeX{} DVI content of this website</a> 
<br>
@end ifset
<br>
@end html

@ifnottex
@menu
* Chapter 1::
* Chapter 2::
* Chapter 3::
* Chapter 4::
* Chapter 5::
* Chapter 6::
* Chapter 7::
* Concept index::	Index of concepts.
@end menu
@end ifnottex

@html
@ifset LongContents
@contents
@end ifset
@ifset ShortContents
@shortcontents
@end ifset
@end html

@node Chapter 1
@unnumbered Chapter 1
@cindex Chapter 1
Hello from Chapter 1.
@section This is Chapter 1 section.
Hello from Chapter 1 section.
@subsection This is Chapter 1 subsection.
Hello from Chapter 1 subsection.
@subsubsection This is Chapter 1 subsubsection.
Hello from Chapter 1 subsubsection.

@node Chapter 2
@unnumbered Chapter 2
@cindex Chapter 2
Hello from Chapter 2.

@node Chapter 3
@unnumbered Chapter 3
@cindex Chapter 3
Hello from Chapter 3.

@node Chapter 4
@unnumbered Chapter 4
@cindex Chapter 4
Hello from Chapter 4.
@section This is Chapter 4 section.
Hello from Chapter 4 section.
@subsection This is Chapter 4 subsection.
Hello from Chapter 4 subsection.
@subsubsection This is Chapter 4 subsubsection.
Hello from Chapter 4 subsubsection.

@node Chapter 5
@unnumbered Chapter 5
@cindex Chapter 5
Hello from Chapter 4.

@node Chapter 6
@unnumbered Chapter 6
@cindex Chapter 6
Hello from Chapter 6.

@node Chapter 7
@unnumbered Chapter 7
@cindex Chapter 7
Test for Chapter 7.
Hello from Chapter 6.

@node Concept index
@unnumbered Concept index
@printindex cp

@bye
