\input texinfo @c -*-texinfo-*-
@c %**start of header
@set Manual JavaScript
@setfilename @value{Manual}.info
@settitle Texinfo Templates

@c Define a new index for options.
@defcodeindex op
@c Combine everything into one index (arbitrarily chosen to be the
@c concept index).
@syncodeindex op cp
@c %**end of header
@c @image{images/open_book_blue,,80pt,Picture of a open book,png}

@copying
This is a template for a manual. Copyright @copyright{} 2012.

@quotation
All right reserved.
@end quotation
@end copying

@dircategory Template
@direntry
* The Texinfo Website Template.               Test
@end direntry

@titlepage
@title Texinfo Website Template
@subtitle for version @today{}
@sp 10
@author @email{anthony_bradford@@yahoo.com,Anthony Bradford}
@page
@vskip 0pt plus 1filll
@insertcopying
@end titlepage

@ifnothtml
@contents
@end ifnothtml

@ifnottex
@node Top
@top Texinfo Website Template Version @today{}
 
This is a Texinfo Website Template. Copyright @copyright{} 2012.
@end ifnottex

@html
@ifset PDF
<a href="@value{Manual}.pdf">PDF content of this website</a>
<br>
@end ifset
@ifset DJVU
<a href="@value{Manual}.djvu">DjVu content of this website</a>
<br>
@end ifset
@ifset SPLIT
<a href="index.html">Split HTML version of this website</a>
<br>
@end ifset
@ifset NOSPLIT
<a href="indexNoSplit.html">Non-Split HTML version of this website</a>
<br>
@end ifset
@ifset TEXT
@cindex Text
@cindex Plain Text
<a href="@value{Manual}.txt">Text content of this website</a> 
<br>
@end ifset
@ifset EPUB
@cindex EPUB
<a href="@value{Manual}.epub">EPUB content of this website</a> 
<br>
@end ifset
@ifset POSTSCRIPT
@cindex PostScript
<a href="@value{Manual}.ps">PostScript content of this website</a> 
<br>
@end ifset
@ifset DVI
@cindex @TeX{} DVI
@cindex DVI
<a href="@value{Manual}.dvi">@TeX{} DVI content of this website</a> 
<br>
@end ifset
@ifset ZIP
@cindex Zip
<a href="@value{Manual}.zip">HTML zip package of this website</a>
<br>
@end ifset
<a href="@value{Manual}.tar.gz">Gzipped tar source of this website</a> 
<br>
<br>
@end html

@ifnottex
@menu
* JavaScript Example::
* Chapter 2::
* Chapter 3::
* Concept index::	Index of concepts.
@end menu
@end ifnottex

@html
@ifset LongContents
@contents
@end ifset
@ifset ShortContents
@shortcontents
@end ifset
@end html

@node JavaScript Example
@chapter JavaScript Example
@cindex JavaScript Example
@ifnothtml
For the JavaScript example see the HTML version of this document.
@end ifnothtml
@html
Web browser must support JavaScript to run. JavaScript may not run on mobile devices.
@end html
@html
<head><title>Cube roots using JavaScript</title>
<center>
<h1>Cube roots using JavaScript</h1>
</center>
<script>
function cubeRoot()
{
	num1 = prompt ("What is the number for which you want the cube root?", "Enter number here");
	document.write (num1);
	document.write ("<br>");
	document.write ("is the number submitted");
	document.write ("<hr>");
	var T = 0;
	var N = parseFloat (num1);
	if (N < 0) {
		N = -N;
		T = 1;
	}
	var M = Math.sqrt (N);
	var ctr = 1
	while (ctr < 101) {
		var M = M*N;
		var M = Math.sqrt (Math.sqrt(M));
		ctr++;
	}
	document.write ("The cube root of that number is:");
	document.write ("<br>");
	if (T==1) {
		M = -M;
	}
	document.write (M);
}
</script>
</head>
<body>
<center>
<button onclick="cubeRoot()">Run JavaScript Program</button>
</center>
</body>
</html>
@end html

@node Chapter 2
@chapter Chapter 2
@cindex Chapter 2
Hello from Chapter 2.

@node Chapter 3
@chapter Chapter 3
@cindex Chapter 3
Hello from Chapter 3.

@node Concept index
@unnumbered Concept index
@printindex cp

@bye
